/**
 * DEMO DATA — development catalogue only (DATABASE.md §12, master §77).
 * Titles are generic (no real-world book titles); there are no reviews, testimonials or sales
 * figures. Prices are illustrative per-currency price rows.
 */
export type DemoProduct = {
  slug: string;
  type: "book" | "guide" | "workbook" | "free_resource";
  title: string;
  subtitle: string;
  category: string;
  extraCategories?: string[];
  spine: string;
  inr: number;
  usd: number;
  inrCompare?: number;
  usdCompare?: number;
  level: string;
  tags: string[];
  featured?: boolean;
  version?: string;
  daysAgo: number;
  chapters: string[];
  inside: { title: string; description: string; icon: string }[];
};

export const DEMO_CATEGORIES = [
  { slug: "productivity", name: "Productivity", description: "Get more done with practical systems and tools.", icon: "timer" },
  { slug: "self-improvement", name: "Self Improvement", description: "Build better habits and a better you.", icon: "sprout" },
  { slug: "career", name: "Career", description: "Grow your skills and advance your career.", icon: "briefcase" },
  { slug: "business", name: "Business", description: "Practical knowledge for builders and entrepreneurs.", icon: "landmark" },
  { slug: "finance", name: "Finance", description: "Manage money and build financial freedom.", icon: "piggy-bank" },
  { slug: "student", name: "Student", description: "Study smarter and achieve more.", icon: "graduation-cap" },
  { slug: "health", name: "Health", description: "Build a healthier and happier life.", icon: "heart-pulse" },
  { slug: "lifestyle", name: "Lifestyle", description: "Design a life you love.", icon: "armchair" },
  { slug: "technology", name: "Tech & Design", description: "Learn modern tools and creative skills.", icon: "laptop" },
];

const inside = {
  basics: { title: "The Foundations", description: "Core ideas explained clearly, step by step.", icon: "book-open" },
  tools: { title: "Essential Tools", description: "Recommended tools and how to use them well.", icon: "wrench" },
  practice: { title: "Practical Exercises", description: "Short exercises to apply each idea.", icon: "pencil" },
  templates: { title: "Templates & Checklists", description: "Ready-to-use pages you can copy.", icon: "clipboard-list" },
  planning: { title: "Planning Pages", description: "Weekly and monthly planning spreads.", icon: "calendar" },
  review: { title: "Reflection & Review", description: "Prompts to look back and adjust.", icon: "refresh-cw" },
};

export const DEMO_PRODUCTS: DemoProduct[] = [
  {
    slug: "the-internet-field-guide",
    type: "book",
    title: "The Internet Field Guide",
    subtitle: "A complete guide to the digital world — tools, concepts and practical skills for everyday use.",
    category: "technology",
    extraCategories: ["productivity"],
    spine: "#1F3B4D",
    inr: 79900,
    usd: 1299,
    inrCompare: 129900,
    usdCompare: 1999,
    level: "Beginner to Advanced",
    tags: ["internet", "digital skills", "tools", "online safety"],
    featured: true,
    version: "2.1",
    daysAgo: 20,
    chapters: ["What Is the Internet?", "How the Web Works", "Browsers and Search", "Online Safety", "Cloud Storage", "Communication Tools", "Working Online", "Careers and Opportunities"],
    inside: [inside.basics, inside.tools, inside.practice],
  },
  {
    slug: "keyboard-shortcuts-handbook",
    type: "guide",
    title: "Keyboard Shortcuts Handbook",
    subtitle: "Save hours every week with the shortcuts that matter across popular apps.",
    category: "productivity",
    spine: "#24504F",
    inr: 49900,
    usd: 799,
    level: "All levels",
    tags: ["shortcuts", "productivity", "software"],
    featured: true,
    daysAgo: 35,
    chapters: ["Why Shortcuts Matter", "System Shortcuts", "Browser Shortcuts", "Writing Apps", "Spreadsheets", "Design Tools", "Building the Habit"],
    inside: [inside.tools, inside.templates],
  },
  {
    slug: "life-planner-workbook",
    type: "workbook",
    title: "Life Planner Workbook",
    subtitle: "A guided workbook to set goals, plan your weeks and review your progress.",
    category: "self-improvement",
    extraCategories: ["productivity"],
    spine: "#5A5A2E",
    inr: 59900,
    usd: 999,
    level: "All levels",
    tags: ["planning", "goals", "habits"],
    featured: true,
    daysAgo: 12,
    chapters: ["Your Values", "Yearly Vision", "Quarterly Goals", "Weekly Planning", "Habit Tracker", "Monthly Review"],
    inside: [inside.planning, inside.templates, inside.review],
  },
  {
    slug: "the-creator-roadmap",
    type: "book",
    title: "The Creator Roadmap",
    subtitle: "Turn your skills into digital products and an audience that trusts you.",
    category: "business",
    spine: "#3B2A20",
    inr: 69900,
    usd: 1199,
    level: "Intermediate",
    tags: ["creators", "digital products", "audience"],
    featured: true,
    daysAgo: 40,
    chapters: ["Finding Your Niche", "Your First Product", "Pricing", "Building an Audience", "Launching", "Systems for Consistency"],
    inside: [inside.basics, inside.practice, inside.templates],
  },
  {
    slug: "digital-declutter-guide",
    type: "guide",
    title: "Digital Declutter Guide",
    subtitle: "Calm your devices, inbox and attention with a simple 30-day reset.",
    category: "lifestyle",
    spine: "#6B2A3A",
    inr: 49900,
    usd: 799,
    inrCompare: 69900,
    usdCompare: 1099,
    level: "Beginner",
    tags: ["focus", "minimalism", "digital wellbeing"],
    featured: true,
    daysAgo: 28,
    chapters: ["Noticing the Noise", "The 30-Day Reset", "Your Phone", "Your Inbox", "Your Files", "Keeping It Calm"],
    inside: [inside.basics, inside.practice],
  },
  {
    slug: "modern-career-playbook",
    type: "book",
    title: "Modern Career Playbook",
    subtitle: "Practical strategies to grow your skills, reputation and opportunities.",
    category: "career",
    spine: "#9A4A2A",
    inr: 45900,
    usd: 799,
    level: "All levels",
    tags: ["career", "skills", "interviews"],
    featured: true,
    daysAgo: 55,
    chapters: ["Mapping Your Career", "Skills That Compound", "Your Portfolio", "Networking Without Awkwardness", "Interviews", "Negotiation"],
    inside: [inside.basics, inside.practice, inside.templates],
  },
  {
    slug: "ai-tools-handbook",
    type: "guide",
    title: "AI Tools Handbook",
    subtitle: "Use AI assistants responsibly for research, writing and everyday work.",
    category: "technology",
    spine: "#1F3B4D",
    inr: 69900,
    usd: 1199,
    level: "Beginner to Intermediate",
    tags: ["ai", "tools", "productivity"],
    daysAgo: 3,
    chapters: ["What AI Assistants Can Do", "Writing Good Prompts", "Research Workflows", "Writing Workflows", "Checking the Output", "Using AI Responsibly"],
    inside: [inside.tools, inside.practice],
  },
  {
    slug: "freelancer-toolkit",
    type: "workbook",
    title: "Freelancer Toolkit",
    subtitle: "Proposals, pricing sheets and client systems for independent work.",
    category: "business",
    extraCategories: ["career"],
    spine: "#B7832F",
    inr: 49900,
    usd: 899,
    level: "Intermediate",
    tags: ["freelancing", "clients", "pricing"],
    daysAgo: 5,
    chapters: ["Positioning", "Pricing Your Work", "Proposals", "Contracts Checklist", "Client Onboarding", "Invoicing"],
    inside: [inside.templates, inside.planning],
  },
  {
    slug: "exam-prep-system",
    type: "workbook",
    title: "Exam Prep System",
    subtitle: "A study planner with spaced revision and practice-test tracking.",
    category: "student",
    spine: "#2F4A3A",
    inr: 49900,
    usd: 799,
    level: "Students",
    tags: ["study", "exams", "students"],
    daysAgo: 6,
    chapters: ["Planning Your Syllabus", "Spaced Revision", "Active Recall", "Practice Tests", "Exam Week", "After the Exam"],
    inside: [inside.planning, inside.templates, inside.review],
  },
  {
    slug: "habit-builder-workbook",
    type: "workbook",
    title: "Habit Builder Workbook",
    subtitle: "Design small habits that stick, with trackers and weekly reflections.",
    category: "self-improvement",
    spine: "#24504F",
    inr: 59900,
    usd: 999,
    level: "All levels",
    tags: ["habits", "trackers", "reflection"],
    featured: true,
    daysAgo: 8,
    chapters: ["Start Tiny", "Habit Stacking", "Your Environment", "Tracking", "When You Slip", "Weekly Reflection"],
    inside: [inside.templates, inside.review],
  },
  {
    slug: "design-practice-workbook",
    type: "workbook",
    title: "Design Practice Workbook",
    subtitle: "Thirty exercises to sharpen layout, typography and colour skills.",
    category: "technology",
    spine: "#9A4A2A",
    inr: 59900,
    usd: 999,
    level: "Beginner to Intermediate",
    tags: ["design", "typography", "practice"],
    daysAgo: 10,
    chapters: ["Seeing Like a Designer", "Layout", "Typography", "Colour", "Composition", "Critique"],
    inside: [inside.practice, inside.templates],
  },
  {
    slug: "student-planner-hub",
    type: "workbook",
    title: "Student Planner Hub",
    subtitle: "Semester planning, assignments and notes in one organised system.",
    category: "student",
    extraCategories: ["productivity"],
    spine: "#1F3B4D",
    inr: 49900,
    usd: 799,
    level: "Students",
    tags: ["students", "planning", "notes"],
    daysAgo: 14,
    chapters: ["Semester Overview", "Assignment Tracker", "Class Notes", "Weekly Planner", "Grade Tracker"],
    inside: [inside.planning, inside.templates],
  },
  {
    slug: "productivity-system-workbook",
    type: "workbook",
    title: "Productivity System Workbook",
    subtitle: "Build a personal productivity system you'll actually keep using.",
    category: "productivity",
    spine: "#B7832F",
    inr: 49900,
    usd: 899,
    inrCompare: 69900,
    usdCompare: 1199,
    level: "All levels",
    tags: ["productivity", "systems", "planning"],
    featured: true,
    daysAgo: 25,
    chapters: ["Capture", "Clarify", "Organise", "Review", "Focus Blocks", "Your Weekly Reset"],
    inside: [inside.planning, inside.templates, inside.review],
  },
  {
    slug: "focus-and-time-blocking-guide",
    type: "guide",
    title: "Focus & Time Blocking Guide",
    subtitle: "Protect your best hours with a simple, flexible calendar method.",
    category: "productivity",
    spine: "#2F4A3A",
    inr: 39900,
    usd: 699,
    level: "All levels",
    tags: ["focus", "calendar", "time management"],
    daysAgo: 45,
    chapters: ["Why Time Blocking Works", "Your Ideal Week", "Blocking Your Calendar", "Handling Interruptions", "Reviewing"],
    inside: [inside.basics, inside.planning],
  },
  {
    slug: "personal-finance-starter",
    type: "book",
    title: "Personal Finance Starter",
    subtitle: "Budgeting, saving and investing basics explained without jargon.",
    category: "finance",
    spine: "#5A5A2E",
    inr: 59900,
    usd: 999,
    level: "Beginner",
    tags: ["money", "budgeting", "saving"],
    daysAgo: 60,
    chapters: ["Your Money Picture", "A Budget That Works", "Emergency Fund", "Debt", "Investing Basics", "Long-Term Planning"],
    inside: [inside.basics, inside.templates],
  },
  {
    slug: "finance-tracker-workbook",
    type: "workbook",
    title: "Finance Tracker Workbook",
    subtitle: "Monthly budgets, expense logs and savings goals in printable pages.",
    category: "finance",
    spine: "#B7832F",
    inr: 49900,
    usd: 799,
    level: "All levels",
    tags: ["money", "trackers", "budgeting"],
    daysAgo: 18,
    chapters: ["Monthly Budget", "Expense Log", "Savings Goals", "Bill Calendar", "Year in Review"],
    inside: [inside.templates, inside.review],
  },
  {
    slug: "health-and-wellness-workbook",
    type: "workbook",
    title: "Health & Wellness Workbook",
    subtitle: "Track sleep, movement and meals with gentle weekly check-ins.",
    category: "health",
    spine: "#24504F",
    inr: 49900,
    usd: 799,
    level: "All levels",
    tags: ["health", "habits", "wellness"],
    daysAgo: 22,
    chapters: ["Your Baseline", "Sleep", "Movement", "Meals", "Stress", "Weekly Check-in"],
    inside: [inside.planning, inside.review],
  },
  {
    slug: "writing-online-guide",
    type: "guide",
    title: "Writing Online Guide",
    subtitle: "Write clearly for blogs, newsletters and social media.",
    category: "business",
    extraCategories: ["career"],
    spine: "#6B2A3A",
    inr: 44900,
    usd: 799,
    level: "Beginner",
    tags: ["writing", "content", "newsletters"],
    daysAgo: 2,
    chapters: ["Clear Thinking, Clear Writing", "Headlines", "Structure", "Editing", "Publishing Consistently"],
    inside: [inside.basics, inside.practice],
  },
  {
    slug: "daily-planner-template",
    type: "free_resource",
    title: "Daily Planner Template",
    subtitle: "A free one-page daily planner to start your day with intention.",
    category: "productivity",
    spine: "#3B2A20",
    inr: 0,
    usd: 0,
    level: "All levels",
    tags: ["free", "planner", "template"],
    daysAgo: 30,
    chapters: ["Daily Planner"],
    inside: [inside.templates],
  },
  {
    slug: "reading-log",
    type: "free_resource",
    title: "Reading Log",
    subtitle: "Track the books you read and the ideas worth keeping — free.",
    category: "self-improvement",
    spine: "#1F3B4D",
    inr: 0,
    usd: 0,
    level: "All levels",
    tags: ["free", "reading", "template"],
    daysAgo: 32,
    chapters: ["Reading Log"],
    inside: [inside.templates],
  },
  {
    slug: "goal-setting-worksheet",
    type: "free_resource",
    title: "Goal Setting Worksheet",
    subtitle: "A free worksheet to turn a big goal into weekly actions.",
    category: "self-improvement",
    spine: "#9A4A2A",
    inr: 0,
    usd: 0,
    level: "All levels",
    tags: ["free", "goals", "worksheet"],
    daysAgo: 33,
    chapters: ["Goal Setting Worksheet"],
    inside: [inside.templates],
  },
];

/** Sellable bundles (C3): fixed price over a set of products. Savings are derived. */
export const DEMO_BUNDLES = [
  {
    slug: "productivity-bundle",
    title: "Productivity Bundle",
    subtitle: "Build better habits, manage your time and get things done with proven systems.",
    category: "productivity",
    spine: "#B7832F",
    items: ["productivity-system-workbook", "keyboard-shortcuts-handbook", "focus-and-time-blocking-guide", "habit-builder-workbook"],
    inr: 129900,
    usd: 2199,
    daysAgo: 15,
  },
  {
    slug: "student-success-bundle",
    title: "Student Success Bundle",
    subtitle: "Everything a student needs to plan, study and excel.",
    category: "student",
    spine: "#2F4A3A",
    items: ["exam-prep-system", "student-planner-hub", "focus-and-time-blocking-guide"],
    inr: 99900,
    usd: 1699,
    daysAgo: 9,
  },
  {
    slug: "creator-bundle",
    title: "Creator Bundle",
    subtitle: "Practical resources to build, launch and grow as an independent creator.",
    category: "business",
    spine: "#3B2A20",
    items: ["the-creator-roadmap", "writing-online-guide", "freelancer-toolkit"],
    inr: 119900,
    usd: 1999,
    daysAgo: 4,
  },
];

/** Editorial collections (C3) — curated groupings that may link to a bundle. */
export const DEMO_COLLECTIONS = [
  {
    slug: "build-your-digital-life",
    title: "Build Your Digital Life",
    description: "Essential books and resources to organise your digital life and get more done.",
    category: "productivity",
    badge: "Most Popular",
    featured: true,
    bundle: null,
    items: ["the-internet-field-guide", "keyboard-shortcuts-handbook", "digital-declutter-guide", "ai-tools-handbook", "productivity-system-workbook", "focus-and-time-blocking-guide"],
  },
  {
    slug: "student-success-kit",
    title: "Student Success Kit",
    description: "Everything you need to excel in your studies and build strong habits.",
    category: "student",
    badge: "Best Value",
    featured: true,
    bundle: "student-success-bundle",
    items: ["exam-prep-system", "student-planner-hub", "focus-and-time-blocking-guide", "habit-builder-workbook"],
  },
  {
    slug: "career-growth",
    title: "Career Growth",
    description: "Practical resources to build skills, get opportunities and grow in your career.",
    category: "career",
    badge: "New Release",
    featured: true,
    bundle: null,
    items: ["modern-career-playbook", "writing-online-guide", "freelancer-toolkit", "ai-tools-handbook"],
  },
  {
    slug: "creative-professional",
    title: "Creative Professional",
    description: "Tools, guides and inspiration for designers, creators and builders.",
    category: "technology",
    badge: null,
    featured: false,
    bundle: "creator-bundle",
    items: ["design-practice-workbook", "the-creator-roadmap", "writing-online-guide"],
  },
  {
    slug: "money-and-wellbeing",
    title: "Money & Wellbeing",
    description: "Calm, practical guides for your finances and your health.",
    category: "finance",
    badge: null,
    featured: false,
    bundle: null,
    items: ["personal-finance-starter", "finance-tracker-workbook", "health-and-wellness-workbook"],
  },
];

export const PRODUCT_FAQS = [
  {
    question: "Is this a physical book or a digital product?",
    answer: "It's a digital product. You'll get instant access to download the file and read it in your KRM.lib library.",
  },
  {
    question: "How will I receive the product after purchase?",
    answer: "As soon as your payment is confirmed, the product appears in My Library and Downloads, and we email you a confirmation.",
  },
  {
    question: "Can I download the product multiple times?",
    answer: "Yes. Each product can be downloaded several times from your Download Center; the exact limit is shown there.",
  },
  {
    question: "Will I get updates when a new version is released?",
    answer: "Yes. When we publish a new version, you'll see an update badge in your library and can download the latest file.",
  },
];
